      - name: 触发部署到腾讯云函数
       if: env.PAT 
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ env.PAT }}" \
            -d '{"ref":"master"}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/deploy_tencent_scf.yml/dispatches
      - name: Notify To Telegram
        if: env.DEPLOY_TG_USER_ID && env.DEPLOY_TG_BOT_TOKEN
        run: |
          curl \
            -s -o /dev/null \
            -X POST \
            -H "Content-Type: application/json" \
            -d '{"text": "${{github.workflow}} 完成！","chat_id": "${{ env.DEPLOY_TG_USER_ID }}"}' \
            https://api.telegram.org/bot${{ env.DEPLOY_TG_BOT_TOKEN }}/sendMessage
      
      - name: Notify To Server酱
        if: env.DEPLOY_PUSH_KEY
        run: |
          curl -s -o /dev/null -X POST https://sc.ftqq.com/${{ env.DEPLOY_PUSH_KEY }}.send \
          -H "Content-Type: application/x-www-form-urlencoded" \
          --data 'text=${{ github.workflow }} 完成！&desp=${{ github.workflow }} 完成！'
